# Generated by Django 3.1.2 on 2020-10-29 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='To_Do',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('time_creation', models.TimeField(auto_now_add=True)),
                ('start_day', models.DateField(default=django.utils.timezone.now)),
                ('end_day', models.DateField(default=django.utils.timezone.now)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ToDo',
                'verbose_name_plural': 'ToDos',
            },
        ),
    ]
