# Generated by Django 3.1.2 on 2020-11-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20201101_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do',
            name='time_creation',
            field=models.DateTimeField(),
        ),
    ]
